spring:
  kafka:
    properties:
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:SCRAM-SHA-256}
      sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_SASL_USERNAME}" password="${KAFKA_SASL_PASSWORD}";'
      ssl.truststore.location: ${KAFKA_SSL_TRUSTSTORE_LOCATION}
      ssl.truststore.type: ${KAFKA_SSL_TRUSTSTORE_TYPE:PEM}
