import type { PortfolioData, Project } from "@/types/portfolio";

const now = new Date(0).toISOString();

const fallbackProjects: Project[] = [
  {
    id: "fallback-caraoque",
    slug: "caraoque",
    name: "Caraôque?",
    status: "Em produção",
    statusEn: "Production",
    shortDescription: "Plataforma Full Stack de karaokê para sessões, fila, músicas, pontuação e ranking.",
    shortDescriptionEn: "Full-stack karaoke platform for sessions, queues, songs, scoring, and rankings.",
    description: "Plataforma Full Stack de karaokê criada para gerenciar uma sessão completa, desde a organização do evento e da fila de participantes até pesquisa de músicas, reprodução, avaliação vocal, pontuação, ranking e histórico de apresentações.",
    descriptionEn: "A full-stack karaoke platform created to manage an entire session, from event organization and participant queues to song search, playback, vocal assessment, scoring, rankings, and performance history.",
    technologies: ["React", "Vite", "Node.js", "Express", "PostgreSQL", "Neon", "YouTube Data API", "Mercado Pago", "Cloudflare"],
    repositoryUrl: "",
    liveUrl: "https://clubkaraoke.uk/",
    featured: true,
    architectureDescription: "A solução separa experiência React, API Node.js/Express e persistência PostgreSQL. As integrações externas ficam isoladas para reduzir acoplamento com YouTube Data API, Mercado Pago, Neon e Cloudflare.",
    architectureDescriptionEn: "The solution separates the React experience, Node.js/Express API, and PostgreSQL persistence. External integrations are isolated to reduce coupling with YouTube Data API, Mercado Pago, Neon, and Cloudflare.",
    highlights: [
      "Controle de sessões, participantes e fila de apresentações.",
      "Busca de músicas integrada ao YouTube Data API.",
      "Avaliação vocal, pontuação e ranking da sessão.",
      "Integração com Mercado Pago e deploy público com Cloudflare.",
    ],
    highlightsEn: [
      "Session, participant, and singing queue control.",
      "Song search integrated with YouTube Data API.",
      "Vocal assessment, scoring, and session ranking.",
      "Mercado Pago integration and public deployment with Cloudflare.",
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "fallback-nexo",
    slug: "nexo-financeiro",
    name: "Nexo Financeiro",
    status: "Em desenvolvimento",
    statusEn: "In development",
    shortDescription: "Controle financeiro pessoal com autenticação, dashboard e gerenciamento de despesas.",
    shortDescriptionEn: "Personal finance management with authentication, dashboard, and expense management.",
    description: "Aplicação de controle financeiro pessoal para centralizar renda, despesas e visão financeira em uma experiência simples e responsiva.",
    descriptionEn: "A personal finance application designed to centralize income, expenses, and financial insights in a simple, responsive experience.",
    technologies: ["React", "Vite", "Supabase", "TailwindCSS", "PWA", "Recharts"],
    repositoryUrl: "",
    liveUrl: "https://nexo-financeiro.netlify.app/",
    featured: false,
    architectureDescription: "Aplicação React com Vite, autenticação e serviços pelo Supabase, suporte PWA e visualizações financeiras com Recharts.",
    architectureDescriptionEn: "React application with Vite, authentication and services through Supabase, PWA support, and financial visualizations with Recharts.",
    highlights: [],
    highlightsEn: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "fallback-vidaplus",
    slug: "vidaplus",
    name: "VidaPlus",
    status: "Projeto acadêmico / TCC",
    statusEn: "Academic project / Final project",
    shortDescription: "Protótipo front-end de gestão hospitalar e serviços de saúde.",
    shortDescriptionEn: "Front-end prototype for hospital and healthcare services management.",
    description: "Protótipo front-end de um sistema de gestão hospitalar, com fluxos para pacientes, profissionais, agendamentos, prescrições, leitos, estoque e relatórios.",
    descriptionEn: "Front-end prototype of a hospital management system with workflows for patients, professionals, appointments, prescriptions, beds, inventory, and reports.",
    technologies: ["JavaScript", "HTML5", "CSS3", "sql.js", "localStorage"],
    repositoryUrl: "https://github.com/AlanChristofer/VidaPlus",
    liveUrl: "https://alanchristofer.github.io/VidaPlus/",
    featured: false,
    architectureDescription: "O sistema funciona no navegador com JavaScript, HTML e CSS, usando sql.js e localStorage para simular persistência sem backend.",
    architectureDescriptionEn: "The system runs in the browser with JavaScript, HTML, and CSS, using sql.js and localStorage to simulate persistence without a backend.",
    highlights: [],
    highlightsEn: [],
    createdAt: now,
    updatedAt: now,
  },
];

/** Evita quebrar a navegação quando a API local ainda não devolve os dados do portfólio. */
export const fallbackData: PortfolioData = {
  profile: {
    id: "profile",
    name: "Alan Christofer",
    role: "Software Developer",
    headline: "Backend • Full Stack • APIs • Arquitetura",
    bio: "Desenvolvedor de software com experiência na criação e evolução de sistemas corporativos, APIs, integrações, automações e aplicações Full Stack.",
    location: "",
    githubUrl: "https://github.com/AlanChristofer/AlanChristofer",
    linkedinUrl: "https://www.linkedin.com/in/alan-christofer-700612227",
    resumeUrl: "",
  },
  skills: [],
  experiences: [],
  projects: fallbackProjects,
};
